% This is an example to automate entire Eddy detection and tracking software
% and also to visualize outputs. Each section elucidates different aspect
% of automatization.
clc; clear
% =====Input arguments for set_up_data_regional=====%
NetCDF_files_path = '~/Desktop/Satellite_data/MADT-SLA/';
ssh_NetCDF_name = 'sla';
lat_NetCDF_name = 'lat';
lon_NetCDF_name = 'lon';
lonlimit = [100, 175];
latlimit = [-35, -70];
ssh_save_path = '~/Documents/MATLAB/OceanEddies-master/Myssh';
%=======
% Preprocessing data for complete run
set_up_NRTdata_regional(NetCDF_files_path, ssh_NetCDF_name, lat_NetCDF_name, lon_NetCDF_name, ...
    lonlimit, latlimit, ssh_save_path)

%% Detection and tracking of eddies
clear;
% =====Input arguments for complete_run=====%
% My SLA data archived in \textbf{Myssh} directory 
ssh_path = '~/Documents/MATLAB/OceanEddies-master/Myssh/';
% I save my outputs at \textbf{MyRuns/MyEddies} and \textbf{MyTracks} directories. 
% Note: Both directory will be generated by script if not exist at provided location. 
% Furthermore, it will also generate directories for modified eddies and track if you 
% had allowed eddy to unassociate. i.e 'yes' at fake eddy argument. 
eddies_save_path = '~/Documents/MATLAB/OceanEddies-master/MyRuns/MyEddies/eddies'; 
tracks_save_path = '~/Documents/MATLAB/OceanEddies-master/MyRuns/MyTracks/tracks';
% These are extra outputs more detail please follow up text in section 3
viewer_data_save_path = '~/Documents/MATLAB/OceanEddies-master/MyRuns/';
viewer_path = '~/Documents/MATLAB/OceanEddies-master/MyRuns/Extra_viewer/';
%========
% running software
complete_run(ssh_path, eddies_save_path, tracks_save_path, 'yes', viewer_data_save_path, viewer_path)

%% Visualization of eddies track after filtering by lifespan
clear;
% =====Input arguments for plotTrack=====%
path = '~/Documents/MATLAB/OceanEddies-master/MyRuns/modified_tracks';
cycfilename = 'cyclonic_tracks_processed.mat';
acycfilename = 'anticyc_tracks_processed.mat';
load([path, cycfilename])
load([path, acyfilename])
% I would filter eddies whose lifespan is \geq 28days
filter_day = 28;
% global_coastline.txt file contains global longitudes and latitude
coast = load('global_coastline.txt');
xtick = 100:10:175;
ytick = -70:5:-35;
%======
% Filtering and plotting
plotTrack(cyclonic_tracks, anticyc_tracks, filter_day, coast, xtick, ytick)