function eddy = mod_new_eddy(STATS, amplitude, lat, lon, thresh, sa, cyc, geospeed, extrema_num, detect)
%NEW_EDDY Initializes new eddy objects, run with no arguments to create an
%empty matrix
    if nargin
        eddy = struct('Stats', STATS, ...
            'Lat', lat, ...
            'Lon', lon, ...
            'Amplitude', amplitude, ...
            'ThreshFound', thresh, ...
            'SurfaceArea', sa, ...
            'Date', NaN, ...
            'Cyc', cyc, ...
            'MeanGeoSpeed', geospeed, ...
            'NumberOfExtrema', extrema_num, ...
            'DetectedBy', detect);
    else
        eddy = struct('Stats', {}, ...
            'Lat', {}, ...
            'Lon', {}, ...
            'Amplitude', {}, ...
            'ThreshFound', {}, ...
            'SurfaceArea', {}, ...
            'Date', {}, ...
            'Cyc', {}, ...
            'MeanGeoSpeed', {}, ...
            'NumberOfExtrema', {}, ...
            'DetectedBy', {});
    end
end