function coast_handle = draw_coast_line(viewer_axis_handle, coast_color)
    coast = load('coast');
    coast_handle = geoshow(coast.lat, coast.long, ...
        'DisplayType', 'polygon', ...
        'FaceColor', coast_color, ...
        'Parent', viewer_axis_handle);
end
