function initializeDateBoxPanel( horizontalBar, bottom_left, panel_size, hdls, fontSize)
%INITIALIZEDATEBOXPANEL Initialize a date box panel where the current date is displayed
%   Detailed explanation goes here

dateBoxPanel = uipanel(horizontalBar, 'Units', 'normalized', 'Position', [bottom_left panel_size]);

uicontrol(dateBoxPanel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0 .5 1 .5], ...
    'FontSize', fontSize, ...
    'String', 'Current Date:');

hdls.dateTextBox = uicontrol(dateBoxPanel, ...
    'Style', 'text', ...
    'Units', 'normalized',...
    'Position', [0 0 1 .5], ...
    'FontSize', fontSize, ...
    'String', '');

end

