function eddy_plot_handle = ...
        plot_eddies(axis_handle, eddy_bodies, marker, color, marker_size, is_filled)
% Plot the eddies on the world map
    if(isempty(eddy_bodies))
        eddy_plot_handle = plotm([NaN NaN],...
                    'Color', color,...
                    'Marker', marker,...
                    'MarkerSize', marker_size,...
                    'Parent', axis_handle,...
                    'LineStyle', 'none');

        return;
    end

    if is_filled
        marker_face_color = color;
    else
        marker_face_color = 'none';
    end

    eddy_plot_handle = plotm(eddy_bodies(:, 1:2),...
                    'Color', color,...
                    'Marker', marker,...
                    'MarkerSize', marker_size,...
                    'MarkerFaceColor', marker_face_color,...
                    'Parent', axis_handle,...
                    'LineStyle', 'none');
end
